### ISSUE TITLE
Redmine not starting after installation

### ISSUE THREAD

**Issue by hermannkm** [HugoHasenbein/redmine_issue_attachments#6]
After installation on my Redmine startup fails with this error message:

```
Error: The application encountered the following error: undefined method `before_filter' for IssueAttachmentQueriesController:Class
Did you mean?  before_action (NoMethodError)
    /var/www/redmine-4.2/plugins/redmine_issue_attachments/app/controllers/issue_attachment_queries_controller.rb:25:in `<class:IssueAttachmentQueriesController>'
    /var/www/redmine-4.2/plugins/redmine_issue_attachments/app/controllers/issue_attachment_queries_controller.rb:23:in `<top (required)>'
```
Additionally ruby zip version required conflicts with some other plugins (easily resolved):

Versions are:
```
Environment:
  Redmine version                4.2.2.stable.21126
  Ruby version                   2.7.2-p137 (2020-10-01) [x86_64-linux]
  Rails version                  5.2.6
  Environment                    production
  Database adapter               Mysql2
  Database timezone              CEST
  ActiveRecord timezone          local
  App timezone                   UTC
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                sendmail
SCM:
  Subversion                     1.13.0
  Git                            2.25.1
  Filesystem                     
Redmine plugins:
  additional_tags                1.0
  additionals                    3.0.3
  easy_gantt                     1.13
  easy_mindmup                   1.0
  easy_wbs                       1.5
  redmine_all_thumbnails         1.0.5
  redmine_checklists             3.1.19
  redmine_custom_workflows       1.0.5
  redmine_dashboard              2.11.0
  redmine_dmsf                   2.4.8 devel
  redmine_drawio                 1.1.3
  redmine_ics_export             4.0.1.dev
  redmine_issue_dynamic_edit     0.7.2
  redmine_local_avatars          1.0.5.2.0
  redmine_mermaid_macro          1.0.0
  redmine_monitoring_controlling 0.1.1
  redmine_more_filters           1.4.4
  redmine_more_previews          2.0.7
  redmine_preview_inline         1.0.3
  redmine_project_themes         1.1.1
  redmine_rtmaterial             0.1.8
  redmine_team_resource          0.4.2
  redmine_tint_issues            1.2.1
  redmine_user_text_box          0.0.1
  redmine_wbs                    1.2.0
  redmine_wiki_lists             0.0.11
  redmine_wiki_sql               0.0.1
  scrum                          0.21.0
```

**Comment by bassofed** [comment]
found [this ](https://stackoverflow.com/questions/45015651/undefined-method-for-before-filter) and it worked for me

`sed -i "s/before_filter/before_action/g" /usr/src/redmine/plugins/redmine_issue_attachments/app/controllers/issue_attachment_queries_controller.rb`

`sed -i "s/before_filter/before_action/g" /usr/src/redmine/plugins/redmine_issue_attachments/app/controllers/issue_attachments_controller.rb`

**Comment by ashrafalzyoud** [comment]
@HugoHasenbein
